"""
api.py
------
FastAPI backend for the PyTorch DAG Optimizer.

Architecture (memory-safe for Render free tier, 512 MB RAM):
  - Built-in model analyses are PRE-COMPUTED offline (via precompute.py).
    At startup the server loads tiny JSON files (~200 KB total) from precomputed/.
    ZERO model loading on Render → ZERO memory spike → no 502s.
  - Custom .py uploads still run live analysis (with memory guards).

Serves:
  GET  /                      → frontend/index.html
  GET  /output/*              → output/ JSON files (backwards compat)
  GET  /api/models            → list of built-in models
  POST /api/analyze           → pre-cached result (built-in) or live analysis (.py)
  GET  /api/downloads/{name}  → serve exported files
"""

from __future__ import annotations

import argparse
import gc
import json
import os
import re
import sys
import time
import traceback
from typing import Any

import torch
import torch.nn as nn
import torchvision.models as tv_models
from fastapi import FastAPI, File, Form, UploadFile
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse
from fastapi.staticfiles import StaticFiles

# ── Path setup ────────────────────────────────────────────────────────────────
ROOT           = os.path.dirname(os.path.abspath(__file__))
FRONTEND_DIR   = os.path.join(ROOT, "frontend")
OUTPUT_DIR     = os.path.join(ROOT, "output")
UPLOADS_DIR    = os.path.join(ROOT, "uploads")
DOWNLOADS_DIR  = os.path.join(ROOT, "downloads")
PRECOMP_DIR    = os.path.join(ROOT, "precomputed")

os.makedirs(UPLOADS_DIR,   exist_ok=True)
os.makedirs(DOWNLOADS_DIR, exist_ok=True)

# ── Limit PyTorch threads on Render's shared CPU ──────────────────────────────
torch.set_num_threads(2)
torch.set_num_interop_threads(1)

sys.path.insert(0, ROOT)
from src.dag_core import ComputationDAG, DAGNode          # noqa: E402
from src.graph_extractor import extract_dag                # noqa: E402
from src.optimizer_agent import GraphState, export         # noqa: E402
from src.optimizer_passes import (                         # noqa: E402
    ConvBNReLUFusionPass,
    DeadNodeEliminationPass,
    ConvBNFoldingPass,
    MemoryFootprintPass,
    PassManager,
)

# ── Built-in model metadata (for /api/models listing) ────────────────────────
# Only 3 models — chosen to fit comfortably within Render's 512 MB free tier.

BUILTIN_MODELS: dict[str, dict[str, Any]] = {
    "resnet18": {
        "display_name": "ResNet-18",
        "input_shape":  [1, 3, 224, 224],
        "description":  "18-layer residual network, 11.7 M params",
    },
    "mobilenet_v2": {
        "display_name": "MobileNet V2",
        "input_shape":  [1, 3, 224, 224],
        "description":  "Inverted-residual mobile architecture, 3.4 M params",
    },
    "squeezenet1_0": {
        "display_name": "SqueezeNet 1.0",
        "input_shape":  [1, 3, 224, 224],
        "description":  "Compact fire-module architecture, 1.2 M params",
    },
}

# ── Load pre-computed results from disk (~200 KB total) ───────────────────────
# These were generated by `python precompute.py` on a machine with enough RAM.
# This is the key to avoiding OOM: zero model loading on Render.

PRECOMPUTED: dict[str, dict] = {}

print("[startup] Loading pre-computed analysis results …")
for model_id in BUILTIN_MODELS:
    json_path = os.path.join(PRECOMP_DIR, f"{model_id}.json")
    if os.path.isfile(json_path):
        with open(json_path, "r", encoding="utf-8") as fh:
            PRECOMPUTED[model_id] = json.load(fh)
        print(f"  ✓ {model_id} cached ({os.path.getsize(json_path) / 1024:.0f} KB)")
    else:
        print(f"  ✗ {model_id} — precomputed/{model_id}.json not found")

print(f"[startup] {len(PRECOMPUTED)}/{len(BUILTIN_MODELS)} models ready "
      f"(zero model loading, zero OOM risk)\n")

# ── Bandwidth math constants ──────────────────────────────────────────────────
BYTES_PER_INTERMEDIATE        = 64 * 112 * 112 * 4
THROUGHPUT_GAIN_PER_CHAIN_PCT = 1.8


# ═════════════════════════════════════════════════════════════════════════════
# FastAPI App
# ═════════════════════════════════════════════════════════════════════════════

app = FastAPI(
    title="PyTorch DAG Optimizer API",
    version="3.1.0",
    description="Memory-safe DAG optimisation with pre-computed model analysis",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# ── Static file serving ──────────────────────────────────────────────────────
app.mount("/output", StaticFiles(directory=OUTPUT_DIR), name="output")


# ── Routes ────────────────────────────────────────────────────────────────────

@app.get("/api/models")
async def list_models():
    """Return the list of built-in models available for analysis."""
    models = []
    for key, info in BUILTIN_MODELS.items():
        models.append({
            "id":           key,
            "display_name": info["display_name"],
            "input_shape":  info["input_shape"],
            "description":  info["description"],
        })
    return {"models": models}


@app.get("/api/downloads/{filename}")
async def download_file(filename: str):
    """Serve a previously exported file from the downloads/ directory."""
    safe = re.sub(r"[^a-zA-Z0-9_\-.]", "_", filename)
    path = os.path.join(DOWNLOADS_DIR, safe)

    if not os.path.isfile(path):
        return JSONResponse(
            status_code=404,
            content={"status": "error", "detail": "File not found."},
        )

    media_type = "application/json" if safe.endswith(".json") else "application/octet-stream"
    return FileResponse(path, media_type=media_type, filename=safe)


@app.post("/api/analyze")
async def analyze_model(
    model_name: str | None       = Form(default=None),
    file:       UploadFile | None = File(default=None),
):
    """
    Analyze a model and return the optimized graph + metrics + download URLs.

    Built-in models: returns pre-computed result instantly (no model loading).
    Custom .py uploads: runs live analysis (small models only).
    """
    upload_path = None
    try:
        # ── Built-in model: serve from pre-computed cache ─────────────────
        if model_name and model_name in BUILTIN_MODELS:
            if model_name in PRECOMPUTED:
                return JSONResponse(content=PRECOMPUTED[model_name])
            else:
                return JSONResponse(
                    status_code=503,
                    content={
                        "status": "error",
                        "detail": (
                            f"Analysis for {model_name} is not available. "
                            f"Pre-computed data was not found on the server."
                        ),
                    },
                )

        # ── Custom .py upload: live analysis ──────────────────────────────
        elif file is not None:
            if not file.filename.endswith(".py"):
                return JSONResponse(
                    status_code=400,
                    content={"status": "error", "detail": "Only .py files are accepted."},
                )
            content = await file.read()
            if len(content) > 1_000_000:
                return JSONResponse(
                    status_code=400,
                    content={"status": "error", "detail": "File too large (max 1 MB)."},
                )

            model, display, input_shape, upload_path = _load_custom_model(
                content, file.filename
            )
            safe_name = re.sub(r"[^a-z0-9]+", "_", display.lower()).strip("_") or "custom"
            result    = _run_live_analysis(model, input_shape, display, safe_name)
            return JSONResponse(content=result)

        else:
            return JSONResponse(
                status_code=400,
                content={
                    "status": "error",
                    "detail": "Provide model_name (built-in) or upload a .py file.",
                },
            )

    except Exception as e:
        traceback.print_exc()
        return JSONResponse(
            status_code=500,
            content={"status": "error", "detail": f"Analysis failed: {str(e)}"},
        )
    finally:
        if upload_path and os.path.isfile(upload_path):
            try:
                os.remove(upload_path)
            except OSError:
                pass


# ═════════════════════════════════════════════════════════════════════════════
# Live analysis (for custom uploads only — NOT used for built-in models)
# ═════════════════════════════════════════════════════════════════════════════

def _run_live_analysis(
    model:       nn.Module,
    input_shape: list[int],
    display:     str,
    safe_name:   str,
) -> dict[str, Any]:
    """Analyze a custom uploaded model. Deletes model before returning."""
    model.eval()

    # ShapeProp with tiny spatial dims to save memory
    sp_shape = list(input_shape)
    if len(sp_shape) >= 4:
        sp_shape[-2] = min(sp_shape[-2], 32)
        sp_shape[-1] = min(sp_shape[-1], 32)
    sp_input = torch.zeros(*sp_shape)

    with torch.no_grad():
        dag = extract_dag(model, sp_input, graph_name=display)
    original_raw = dag.to_json()
    del dag, sp_input
    gc.collect()

    original_n = original_raw["metadata"]["num_nodes"]
    original_e = original_raw["metadata"]["num_edges"]

    # Optimisation pipeline
    pipeline = PassManager([
        ConvBNReLUFusionPass(),
        DeadNodeEliminationPass(),
        ConvBNFoldingPass(),
        MemoryFootprintPass(),
    ])
    gs      = GraphState(original_raw)
    results = pipeline.run(gs)

    optimized_raw = gs.to_json("Optimized")
    final_n = optimized_raw["metadata"]["num_nodes"]
    final_e = optimized_raw["metadata"]["num_edges"]

    fused_count  = sum(1 for n in optimized_raw["nodes"] if n.get("op_type") == "fused_op")
    folded_count = sum(1 for n in optimized_raw["nodes"] if n.get("op_type") == "folded_op")

    rw_eliminated   = fused_count * 2
    bw_freed_bytes  = fused_count * 2 * BYTES_PER_INTERMEDIATE
    bw_cut_pct      = (rw_eliminated / max(original_e * 2, 1)) * 100
    throughput_gain = fused_count * THROUGHPUT_GAIN_PER_CHAIN_PCT
    node_red_pct    = ((original_n - final_n) / max(original_n, 1)) * 100
    edge_red_pct    = ((original_e - final_e) / max(original_e, 1)) * 100

    if bw_freed_bytes >= 1e6:
        bw_human = f"~{bw_freed_bytes / 1e6:.1f} MB"
    elif bw_freed_bytes >= 1e3:
        bw_human = f"~{bw_freed_bytes / 1e3:.1f} KB"
    else:
        bw_human = f"{bw_freed_bytes} B"

    pass_results = []
    for r in results:
        pass_results.append({
            "pass_name":     r.pass_name,
            "nodes_before":  r.nodes_before,
            "nodes_after":   r.nodes_after,
            "edges_before":  r.edges_before,
            "edges_after":   r.edges_after,
            "nodes_removed": r.nodes_removed,
            "edges_removed": r.edges_removed,
            "notes":         r.notes[:10],
        })

    memory = gs.metadata.get("memory_analysis", {})

    # Export JSON for download
    json_filename = f"optimized_graph_{safe_name}.json"
    json_url      = None
    try:
        json_path = os.path.join(DOWNLOADS_DIR, json_filename)
        with open(json_path, "w", encoding="utf-8") as fh:
            json.dump({
                "_export_info": {
                    "tool":        "PyTorch DAG Optimizer",
                    "exported_at": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                    "description": "Optimized computation graph — Kahn's BFS topo-sort.",
                },
                "model_name":      display,
                "optimized_graph": optimized_raw,
                "metrics":         {"fused_ops": fused_count, "folded_ops": folded_count},
                "memory_analysis": memory,
            }, fh, indent=2)
        json_url = f"/api/downloads/{json_filename}"
    except Exception as json_err:
        print(f"[WARN] JSON export failed: {json_err}")

    # Free model
    del model
    gc.collect()

    return {
        "status":     "success",
        "model_name": display,
        "original_graph":  original_raw,
        "optimized_graph": optimized_raw,
        "metrics": {
            "original_nodes":            original_n,
            "original_edges":            original_e,
            "optimized_nodes":           final_n,
            "optimized_edges":           final_e,
            "node_reduction_pct":        round(node_red_pct, 1),
            "edge_reduction_pct":        round(edge_red_pct, 1),
            "fused_ops":                 fused_count,
            "folded_ops":                folded_count,
            "hbm_rw_eliminated":         rw_eliminated,
            "hbm_bandwidth_freed_bytes": bw_freed_bytes,
            "hbm_bandwidth_freed_human": bw_human,
            "hbm_traffic_cut_pct":       round(bw_cut_pct, 1),
            "est_throughput_gain_pct":   round(throughput_gain, 1),
            "pass_results":              pass_results,
        },
        "memory_analysis": memory,
        "downloads": {
            "pt_url":          None,
            "pt_filename":     None,
            "pt_speedup_info": (
                "TorchScript .pt export is available when running locally. "
                "Use: torch.jit.trace(model, x).save('optimized.pt')"
            ),
            "json_url":        json_url,
            "json_filename":   json_filename if json_url else None,
        },
    }


# ── Custom model loader ──────────────────────────────────────────────────────

def _load_custom_model(
    content:  bytes,
    filename: str,
) -> tuple[nn.Module, str, list[int], str]:
    """Load a user-uploaded .py model file dynamically."""
    import importlib.util

    path = os.path.join(UPLOADS_DIR, filename)
    with open(path, "wb") as fh:
        fh.write(content)

    spec = importlib.util.spec_from_file_location("_user_model", path)
    mod  = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)

    if not hasattr(mod, "get_model"):
        raise ValueError(
            "Uploaded .py file must define a `get_model()` function "
            "that returns an nn.Module."
        )

    model = mod.get_model()
    name  = getattr(mod, "MODEL_NAME",  os.path.splitext(filename)[0])
    shape = getattr(mod, "INPUT_SHAPE", [1, 3, 224, 224])
    return model, name, shape, path


# ── Serve frontend ────────────────────────────────────────────────────────────

@app.get("/")
async def serve_index():
    return FileResponse(os.path.join(FRONTEND_DIR, "index.html"))


app.mount("/", StaticFiles(directory=FRONTEND_DIR), name="frontend")


# ── Entry point ───────────────────────────────────────────────────────────────

def main() -> None:
    import uvicorn

    parser = argparse.ArgumentParser(description="PyTorch DAG Optimizer API Server")
    parser.add_argument("--port", type=int, default=None)
    parser.add_argument("--host", default="0.0.0.0")
    args = parser.parse_args()

    port = args.port or int(os.environ.get("PORT", 8080))
    host = args.host

    print()
    print("  ┌─────────────────────────────────────────────────────┐")
    print("  │   PyTorch DAG Optimizer  v3.1  (pre-computed cache) │")
    print(f"  │   http://{host}:{port:<5}                              │")
    print("  └─────────────────────────────────────────────────────┘")
    print()

    uvicorn.run(app, host=host, port=port)


if __name__ == "__main__":
    main()
